name: app_services
description: Platform services (location, permissions, notifications, calls) interfaces for Emergency Super-App
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: